---
# tasks file for monit
- name: install monit
  apt:
    pkg: monit
    state: present

- name: start monit
  service:
    name: monit
    state: started

- name: configure monit
  template:
    src: haproxy.conf
    dest: /etc/monit/conf.d/haproxy
    mode: 0644

- name: restart monit
  service:
    name: monit
    state: restarted
