---
# defaults file for ntp
ntp_servers:
    - "0.ru.pool.ntp.org"
    - "1.ru.pool.ntp.org"
    - "2.ru.pool.ntp.org"
    - "3.ru.pool.ntp.org"

ntp_restrict_policies:
    - "-4 default kod notrap nomodify nopeer noquery"
    - "-6 default kod notrap nomodify nopeer noquery"
    - "127.0.0.1"
    - "-6 ::1"
