---
# tasks file for ntp
- name: Install ntp
  apt:
    pkg: ntp
    state: present

- name: install ntpdate
  apt:
    pkg: ntpdate
    state: present

- name: Configure ntp.conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ntp

- name: start ntp
  service:
    name: ntp
    enabled: yes
    state: started

